# Generated by Django 6.0.5 on 2026-06-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_priority_project_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
