# Generated by Django 6.0 on 2026-06-30 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=20)),
                ('accent_color', models.CharField(default='#0066ff', max_length=7)),
                ('notifications', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('default_dashboard', models.CharField(choices=[('projects', 'Projects'), ('tasks', 'Tasks'), ('calendar', 'Calendar')], default='projects', max_length=20)),
                ('default_calendar_view', models.CharField(choices=[('month', 'Month'), ('week', 'Week'), ('day', 'Day')], default='month', max_length=10)),
                ('task_sorting', models.CharField(default='priority', max_length=20)),
                ('project_sorting', models.CharField(default='created_at', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
