# Generated by Django 6.0 on 2026-06-20 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Task created'), ('updated', 'Task updated'), ('moved', 'Task moved'), ('assignee_added', 'Assignee added'), ('assignee_removed', 'Assignee removed'), ('priority_changed', 'Priority changed'), ('due_date_changed', 'Due date changed'), ('comment_added', 'Comment added'), ('comment_edited', 'Comment edited'), ('comment_deleted', 'Comment deleted'), ('label_added', 'Label added'), ('label_removed', 'Label removed')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional context, e.g., {"from": "Todo", "to": "In Progress"}', null=True)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#cccccc', help_text='Hex color code, e.g., #ff5733', max_length=7)),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_assigne_5c11c7_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='task_labels', to='tasks.label'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
    ]
