# Generated by Django 6.0.5 on 2026-06-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_updated_by_alter_label_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(default='#cccccc', help_text='Hex color code, e.g., #ff5733', max_length=7),
        ),
    ]
